package network

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"

	"docksmith/internal/safepath"
)

// fallbackNameservers are used when the host's resolv.conf yields nothing
// usable inside a container.
var fallbackNameservers = []string{"8.8.8.8", "1.1.1.1"}

// WriteHostFiles generates /etc/resolv.conf, /etc/hostname and /etc/hosts
// inside a container's rootfs.
//
// Without these, networking is only half working in a way that is easy to
// misread: `ping 8.8.8.8` succeeds because routing and NAT are fine, while
// `ping example.com` fails because there is no resolver configuration at all,
// which looks like a NAT bug and is not one.
//
// Called before pivot_root, so paths are relative to the rootfs on the host.
func WriteHostFiles(rootfs, hostname, containerIP string) error {
	if err := writeResolvConf(rootfs); err != nil {
		return err
	}
	if err := writeHostname(rootfs, hostname); err != nil {
		return err
	}
	return writeHosts(rootfs, hostname, containerIP)
}

func writeResolvConf(rootfs string) error {
	servers := hostNameservers()
	if len(servers) == 0 {
		servers = fallbackNameservers
	}
	var b strings.Builder
	b.WriteString("# generated by docksmith\n")
	for _, s := range servers {
		fmt.Fprintf(&b, "nameserver %s\n", s)
	}
	return writeEtcFile(rootfs, "resolv.conf", b.String())
}

// hostNameservers reads the host's resolvers, discarding any that only work
// from the host.
func hostNameservers() []string {
	f, err := os.Open("/etc/resolv.conf")
	if err != nil {
		return nil
	}
	defer f.Close()
	return parseNameservers(f)
}

// parseNameservers extracts the usable nameserver addresses from resolv.conf
// syntax. Split out from hostNameservers so it can be tested against inputs
// this host does not happen to have: the machine docksmith was written on runs
// systemd-resolved and its /etc/resolv.conf contains nothing but 127.0.0.53, so
// a test that read the real file would never exercise the non-loopback path —
// or, on a host without systemd-resolved, never exercise the filter at all.
func parseNameservers(r io.Reader) []string {
	var out []string
	scanner := bufio.NewScanner(r)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) < 2 || fields[0] != "nameserver" {
			continue
		}
		addr := fields[1]
		// A loopback resolver — systemd-resolved's 127.0.0.53 is the common
		// case — refers to a stub listener in the host's network namespace.
		// Inside the container 127.0.0.1 is the container itself, where
		// nothing is listening, so copying it across produces silent DNS
		// timeouts rather than an error.
		if strings.HasPrefix(addr, "127.") || addr == "::1" {
			continue
		}
		out = append(out, addr)
	}
	return out
}

func writeHostname(rootfs, hostname string) error {
	return writeEtcFile(rootfs, "hostname", hostname+"\n")
}

func writeHosts(rootfs, hostname, containerIP string) error {
	var b strings.Builder
	b.WriteString("127.0.0.1\tlocalhost\n")
	b.WriteString("::1\tlocalhost ip6-localhost ip6-loopback\n")
	if containerIP != "" && hostname != "" {
		fmt.Fprintf(&b, "%s\t%s\n", containerIP, hostname)
	}
	return writeEtcFile(rootfs, "hosts", b.String())
}

// writeEtcFile writes a file under the rootfs's /etc, creating the directory
// if the image does not have one.
//
// This runs as root in the host's mount namespace before pivot_root, so the
// path is resolved through safepath rather than joined directly:
// an image shipping `etc -> /` or `etc/hosts -> /root/.ssh/authorized_keys`
// would otherwise have docksmith overwrite host files on its behalf. Any
// existing entry is removed first so a symlink cannot be written through.
func writeEtcFile(rootfs, name, content string) error {
	if _, err := safepath.MkdirAll(rootfs, "etc"); err != nil {
		return fmt.Errorf("creating /etc in rootfs: %w", err)
	}
	path, err := safepath.ResolveNoFollow(rootfs, "etc/"+name)
	if err != nil {
		return fmt.Errorf("writing /etc/%s: %w", name, err)
	}
	os.Remove(path)
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing /etc/%s: %w", name, err)
	}
	return nil
}
