#!/bin/sh
echo "============================================"
echo "  Docksmith Sample App"
echo "============================================"
echo ""
echo "Environment variables:"
echo "  APP_NAME = ${APP_NAME}"
echo "  APP_ENV  = ${APP_ENV}"
echo "  GREETING = ${GREETING}"
echo ""
echo "Working directory: $(pwd)"
echo ""
echo "App files:"
ls -la /app/
echo ""
echo "Settings:"
cat /app/settings.txt
echo ""
echo "Build info:"
cat /app/message.txt 2>/dev/null || echo "  (none)"
echo ""
echo "============================================"
echo "  ${GREETING} from Docksmith!"
echo "============================================"
